### ISSUE TITLE
Version mismatch in composer.json for Git tag v2.0.5

### ISSUE THREAD

**Issue by wexo-team** [edudeleon/webshipr-magento2-shipping#2]
https://github.com/edudeleon/webshipr-magento2-shipping/blob/b7724c4912716f0c39f2fba60e2d04f92225902a/composer.json#L5

The Git tag `v.2.0.5`'s composer.json says is the version is `2.0.4`.
Our Composer repo skips the new version since it can tell for sure what version information is the correct one.

**Comment by edudeleon** [comment]
Thanks for the feedback @wexo-team. I updated the module version. Let me know if your composer repo will work this time. 

Best,

**Comment by wexo-team** [comment]
Thank you @edudeleon, it works now.
